# This is a basic workflow to help you get started with Actions

name: CI
on: [push]

jobs:
  test-job:
    runs-on: ubuntu-latest

    steps:
      - name: GetBranch
        run: |
          echo ${GITHUB_REF#refs/heads/}
